# Generated by Django 3.0.2 on 2020-02-29 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=191)),
                ('visitor_phone', models.CharField(max_length=15)),
                ('visitor_from', models.CharField(max_length=191)),
                ('purpose_of_visit', models.CharField(max_length=191)),
                ('visit_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('check_in', models.DateTimeField(auto_now_add=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='check_out')),
                ('barcode', models.CharField(blank=True, max_length=225, null=True)),
                ('visitor_image', models.TextField(blank=True, max_length=10000, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
        ),
    ]
