# Generated by Django 3.0.2 on 2020-02-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default=None, max_length=191)),
                ('company_phone', models.CharField(default=None, max_length=15)),
                ('company_owner', models.CharField(default=None, max_length=191)),
                ('company_address', models.CharField(default=None, max_length=191)),
                ('contact_person', models.CharField(default=None, max_length=191)),
                ('company_email', models.EmailField(default=None, max_length=254)),
            ],
        ),
    ]
